export  const INCREMENT = 'INCREMENT';
export  const DECREMENT = 'DECREMENT';
export  const RESET = 'RESET';
export const FETCH_BACKGROUND = 'FETCH_BACKGROUND';
export const REQUEST_BACKGROUND = 'REQUEST_BACKGROUND';
export const REQUEST_BACKGROUND_SUCCESS = 'REQUEST_BACKGROUND_SUCCEEDED';
export const REQUEST_BACKGROUND_FAILED = 'REQUEST_BACKGROUND_FAILED';
export const ENABLE_BUTTONS = 'ENABLE_BUTTONS';
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS';


